import React from 'react';
import {
  Checker,
  Dashboard,
  DashboardEmployee,
  EmployeeLayout,
  Attendance,
  RequestLayoutManagement,
  NotificationLayoutManagement,
  Configuration,
  Test,
  ConfigurationModel,
  Information,
  Center,
  ChangePass,
} from 'routes/loadModule';
// import subRoutes from 'containers/Admin/Routes';
import NotFoundPage from 'containers/NotFoundPage/Loadable';
import Icon from 'antd/es/icon';
// import Auth from 'containers/Auth';
const routes = [
  {
    path: '/admin',
    key: 'admin-dashboard',
    exact: true,
    component: Dashboard,
    label: 'Thống kê',
    icon: <Icon type="dashboard" />,
  },
  {
    path: '/admin/dashboard-employee',
    key: 'admin-dashboard-employee',
    exact: true,
    component: DashboardEmployee,
    label: 'Thống kê',
    icon: <Icon type="dashboard" />,
  },
  {
    path: '/admin/test',
    key: 'admin-test',
    exact: true,
    component: Test,
    label: 'Test',
    icon: <Icon type="dashboard" />,
  },
  {
    path: '/admin/employee',
    key: 'admin-employee',
    // exact: true,
    component: EmployeeLayout,
    label: 'Nhân viên',
    icon: <Icon type="team" />,
  },
  {
    path: '/admin/request',
    key: 'admin-request',
    component: RequestLayoutManagement,
    label: 'Yêu cầu',
    icon: <Icon type="clock-circle" />,
  },
  {
    path: '/admin/notification',
    key: 'admin-notification',
    // exact: true,
    component: NotificationLayoutManagement,
    label: 'Thông báo',
    icon: <Icon type="sound" />,
  },
  {
    path: '/admin/checker',
    key: 'admin-checker',
    exact: true,
    component: Checker,
    label: 'Giám sát',
    icon: <Icon type="clock-circle" />,
  },
  {
    path: '/admin/attendance',
    key: 'admin-attendance',
    exact: true,
    component: Attendance,
    label: 'Attendance',
    icon: <Icon type="search" />,
  },
  {
    path: '/admin/configuration',
    key: 'admin-configuration',
    exact: true,
    component: Configuration,
    label: 'Cài đặt hệ thống',
    icon: <Icon type="setting" />,
  },
  {
    path: '/admin/configuration-model',
    key: 'admin-configuration-model',
    exact: true,
    component: ConfigurationModel,
    label: 'Cài đặt mô hình',
    icon: <Icon type="setting" />,
  },
  {
    path: '/admin/user',
    key: 'admin-user',
    routes: [
      {
        path: '/admin/user',
        key: 'admin-user-center',
        label: 'Thông tin cá nhân',
        icon: <Icon type="profile" />,
        exact: true,
        component: Center,
      },
      {
        path: '/admin/user/change-password',
        key: 'admin-user-change-password',
        icon: <Icon type="eye-invisible" />,
        exact: true,
        component: ChangePass,
        label: 'Thay đổi mật khẩu',
      },
    ],
    // exact: true,
    component: Information,
    hidden: true,
    label: 'Thông tin',
    icon: <Icon type="user" />,
  },
  {
    path: '',
    component: NotFoundPage,
  },
];
export default routes;
